#!/usr/bin/env python3
"""Report open breadcrumb stubs — the known-unknowns the model has pointed at itself.

One job. Decision #27 (breadcrumb / cross-reference mining) is how the net widens without
sweeping the whole statute book: when a provision or record names something OUTSIDE what we
hold, that is a lead. The method only works if the leads are TRACKED — otherwise a stub is
closed by whoever happens to notice it, and completeness is a feeling rather than a number.
WIA 1991 s.16 was exactly this: s.16A (the CMA's veto) was extracted without s.16 (the duty
it blocks), and it surfaced only because someone went looking for the veto's target.

DERIVED, not hand-maintained. A hand-kept list would drift out of date the moment a stub was
closed; this reads the records every time, so a closed stub disappears on its own. Four
detectors, each a real completeness gap:

  1. UNTIED VETO      — a veto whose blocked party IS modelled but whose blocked record is
                        not. The chain traverses body-to-body instead of record-to-record.
  2. DANGLING REF     — a Provision.references entry pointing at a provision we do not hold
                        (the classic adjacent-instrument lead).
  3. NARRATIVE STUB   — a record whose own notes flag something deliberately not extracted.
                        Convention: write "breadcrumb stub" or "NOT separately extracted".
  4. ORPHAN INSTRUMENT— an instrument registered with no provisions extracted from it.

Writes issues/breadcrumbs.md and prints a summary. Read-only over data/.

    py -3 pipeline/breadcrumbs.py
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import store

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "issues", "breadcrumbs.md")
STUB_MARKERS = ("breadcrumb stub", "not separately extracted", "not yet extracted",
                "have not extracted", "extraction work item")


def collect():
    powers = store.load("powers")
    duties = store.load("duties")
    vetoes = store.load("vetoes")
    provs = store.load("provisions")
    instruments = store.load("instruments")
    bodies = {b["body_id"]: b["name"] for b in store.load("bodies")}
    record_ids = {p["power_id"] for p in powers} | {d["duty_id"] for d in duties}
    prov_keys = {p["provision_key"] for p in provs}
    rows = []

    # 1. Vetoes that name a modelled blocked party but no blocked record.
    for v in vetoes:
        party = v.get("blocks_body_id") or v.get("blocks_office_id")
        if party and not v.get("blocks_record_id"):
            rows.append(("untied veto", v["veto_id"],
                         f"blocks {bodies.get(party, party)} but names no blocks_record_id — "
                         f"the obstructed power or duty is not extracted"))
        elif v.get("blocks_record_id") and v["blocks_record_id"] not in record_ids:
            rows.append(("untied veto", v["veto_id"],
                         f"blocks_record_id {v['blocks_record_id']} does not resolve"))

    # 2. Cross-references pointing out of what we hold.
    for p in provs:
        for ref in p.get("references") or []:
            target = ref if isinstance(ref, str) else (ref.get("provision_key") or "")
            if target and target not in prov_keys:
                rows.append(("dangling reference", p["provision_key"],
                             f"references {target}, which is not held"))

    # 3. Notes that flag something deliberately left out.
    for rec in powers + duties + vetoes:
        note = (rec.get("notes") or "").lower()
        if any(m in note for m in STUB_MARKERS):
            rid = rec.get("power_id") or rec.get("duty_id") or rec.get("veto_id")
            excerpt = re.sub(r"\s+", " ", (rec.get("notes") or "")).strip()
            rows.append(("narrative stub", rid, excerpt[:300]))

    # 4. Instruments registered but never mined.
    mined = {p["instrument_id"] for p in provs}
    for i in instruments:
        if i["instrument_id"] not in mined:
            rows.append(("orphan instrument", i["instrument_id"],
                         f"{i.get('title')} registered with no provisions extracted"))
    return rows


def main():
    rows = collect()
    by_kind = {}
    for kind, ref, detail in rows:
        by_kind.setdefault(kind, []).append((ref, detail))

    lines = ["# Breadcrumb register — open stubs", "",
             "**Generated by `pipeline/breadcrumbs.py`. Do not edit by hand — rerun it.**", "",
             "Decision #27's breadcrumb method widens the net without sweeping the whole statute "
             "book, but it only works if the leads are tracked. This file is derived from the "
             "records every time it runs, so a stub that has been closed disappears by itself "
             "and the count is a real completeness measure rather than a feeling.", "",
             f"**{len(rows)} open stub(s).**", ""]
    for kind in sorted(by_kind):
        lines.append(f"## {kind} ({len(by_kind[kind])})")
        lines.append("")
        for ref, detail in sorted(by_kind[kind]):
            lines.append(f"- **`{ref}`** — {detail}")
        lines.append("")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    print("--- breadcrumb register ---")
    for kind in sorted(by_kind):
        print(f"  {kind:22} {len(by_kind[kind])}")
    print(f"  {'TOTAL':22} {len(rows)}")
    print(f"  wrote {os.path.relpath(OUT, REPO)}")


if __name__ == "__main__":
    main()
