#!/usr/bin/env python3
"""Mirror §10 (the decision register) of the governing plan into the repo, under Git.

One job. The decision register is the single source of truth (CLAUDE.md), but the governing
plan lives OUTSIDE this repo in the OneDrive workspace, so the register was not version
controlled. This copies §10 verbatim into `docs/decision-register.md` so it is tracked with
the rest of the build. DERIVED, not hand-maintained — re-run it after the plan's §10 changes;
never edit the mirror directly (a `--check` mode fails if the two have diverged, for a hook).

The plan stays authoritative. If the plan file is not reachable (a headless/CI checkout where
the OneDrive parent is absent), this exits 0 without touching the mirror.

    py -3 pipeline/sync_decision_register.py           # refresh the mirror
    py -3 pipeline/sync_decision_register.py --check    # exit 1 if the mirror is stale
"""
import argparse
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLAN = os.path.join(os.path.dirname(REPO), "2026-07-05-state-machine-project-plan-v0-5.md")
MIRROR = os.path.join(REPO, "docs", "decision-register.md")

HEADER = (
    "# Decision register\n\n"
    "**Mirrored, version-controlled copy** of §10 of the governing plan "
    "(`../../2026-07-05-state-machine-project-plan-v0-5.md`), which lives outside this repo in "
    "the OneDrive workspace. The plan remains the authoritative source; this copy exists so the "
    "register is under Git like the rest of the build. **Do not edit this file directly** — run "
    "`pipeline/sync_decision_register.py` after the plan's §10 changes.\n\n"
    "Detailed engineering rationale for the powers-layer decisions is in "
    "`../issues/schema-decisions.md`; this file is the index of truth (decision, default, "
    "status).\n\n")


def render():
    if not os.path.exists(PLAN):
        return None
    with open(PLAN, encoding="utf-8") as fh:
        plan = fh.read()
    m = re.search(r"## 10\. Decision register.*?(?=\n## 11\.)", plan, re.S)
    if not m:
        sys.exit("FAIL: could not locate §10 in the plan")
    body = m.group(0).strip()
    body = re.sub(r"^## 10\. Decision register.*?\n\n", "", body, flags=re.S)
    return HEADER + body + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the mirror is stale")
    args = ap.parse_args()

    want = render()
    if want is None:
        print("plan not reachable (OneDrive parent absent) — mirror left unchanged")
        return
    have = ""
    if os.path.exists(MIRROR):
        with open(MIRROR, encoding="utf-8") as fh:
            have = fh.read()

    if args.check:
        if want != have:
            sys.exit("FAIL: docs/decision-register.md is stale — run "
                     "pipeline/sync_decision_register.py")
        print("decision-register mirror is in sync")
        return

    with open(MIRROR, "w", encoding="utf-8") as fh:
        fh.write(want)
    rows = len(re.findall(r"^\| \d+ \|", want, re.M))
    print(f"synced docs/decision-register.md ({rows} decisions)")


if __name__ == "__main__":
    main()
